{
 "title": "Tezos",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "TZKT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "RPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Bootstrapped",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tezos_node_bootstrapped", "legendFormat": "Bootstrapped" }
   ]
  },
  {
   "title": "Connected peers",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 2, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tezos_node_peers{instance=\"tezos_exporter:9489\",job=\"tezos\",state=\"running\"}"
    }
   ]
  },
  {
   "title": "Connections",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 7, "x": 5, "y": 2 },
   "targets": [
    {
     "expr": "tezos_node_connections{direction=\"incoming\",private=\"false\"}",
     "legendFormat": "Incoming"
    },
    {
     "expr": "tezos_node_connections{direction=\"outgoing\",private=\"false\"}",
     "legendFormat": "Outgoing"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 3, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{image!=\"\",name=\"tezos-node-1\"}[1m])) by (name)",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 4, "x": 15, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_memory_max_usage_bytes{image!=\"\",name=\"tezos-node-1\"}",
     "legendFormat": "{{ name }}"
    }
   ]
  },
  {
   "title": "I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(tezos_node_recv_bytes_total[5m])",
     "legendFormat": "Received bytes"
    },
    {
     "expr": "rate(tezos_node_sent_bytes_total[5m])",
     "legendFormat": "Sent bytes"
    }
   ]
  },
  {
   "title": "Num Ops per Block",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 10, "y": 9 },
   "targets": [
    {
     "expr": "[block.header.timestamp, block.delay / block.minimal_delay]",
     "fields": [
      "header.timestamp",
      "statistics.n_ops_total"
     ]
    }
   ]
  }
 ]
}